#!/usr/bin/env python3
"""
publish_wiki.py — mirror ``docs/wiki/`` into this repo's GitHub wiki (no LLM, stdlib only).

A GitHub wiki is a second git repo (``<repo>.wiki.git``) with a *flat* page namespace: the file
name is the page name, so ``Overview.md`` is served at ``/wiki/Overview``. Our generated pages
don't match that contract — they're lowercase slugs that cross-link by file name
(``[Overview](overview.md)``), which in a wiki resolves to a 404 page named "overview.md". This
script does the translation, then syncs the result.

Two modes, because pushing is destructive:

    python scripts/publish_wiki.py                 # build into build/wiki/ and stop
    python scripts/publish_wiki.py --push          # build, then commit + push to the wiki repo

``--push`` makes the wiki a pure mirror: everything in the wiki repo is deleted and replaced by
the build output, so pages hand-edited in the GitHub web UI are overwritten. That's deliberate —
``docs/wiki/`` is generated from the code graph and is the only source of truth worth keeping.

The wiki repo does not exist until wikis are enabled AND a first page is created in the web UI.
Until then every clone fails with "Repository not found"; see the hint in `clone_wiki`.

No dependency on the `codewiki` package: CI publishes without installing anything.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_WIKI_DIR = REPO_ROOT / "docs" / "wiki"
DEFAULT_OUT_DIR = REPO_ROOT / "build" / "wiki"

HOME_PAGE = "Home"          # GitHub wiki serves this as the wiki's landing page
SIDEBAR_PAGE = "_Sidebar"   # rendered alongside every page
FOOTER_PAGE = "_Footer"

# Markdown links to a sibling page: `](overview.md)` / `](overview.md#anchor)`. Absolute URLs and
# root-relative paths are left alone — the generated source_refs point at github.com/.../blob/...
# and stay valid from anywhere.
_PAGE_LINK_RE = re.compile(r"\]\((?!https?://|/|#)([^)\s#]+)\.md(#[^)\s]*)?\)")


def run(*args: str, cwd: Path | None = None) -> str:
    """Run a git command, raising with stderr attached if it fails."""
    proc = subprocess.run(args, cwd=cwd, capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(f"{' '.join(args)} failed:\n{proc.stderr.strip()}")
    return proc.stdout.strip()


def repo_web_url(remote: str) -> str:
    """``git@github.com:o/r.git`` / ``https://github.com/o/r.git`` -> ``https://github.com/o/r``."""
    url = remote.removesuffix(".git")
    if url.startswith("git@"):
        host, _, path = url.partition(":")
        url = f"https://{host.removeprefix('git@')}/{path}"
    return url


def wiki_name(title: str, *, is_home: bool = False) -> str:
    """Page title -> wiki file stem. GitHub maps spaces to `-` in URLs; do it up front so the
    committed file name and the link text agree."""
    if is_home:
        return HOME_PAGE
    return re.sub(r"\s+", "-", title.strip())


def build_name_map(pages: list[dict]) -> dict[str, str]:
    """slug -> wiki page name. The lowest-ordered page becomes Home; the rest keep their titles."""
    ordered = sorted(pages, key=lambda p: p["order"])
    return {
        page["slug"]: wiki_name(page["title"], is_home=(i == 0))
        for i, page in enumerate(ordered)
    }


def rewrite_links(text: str, name_map: dict[str, str]) -> str:
    """Point sibling-page links at wiki page names instead of file names."""
    def replace(match: re.Match[str]) -> str:
        target, anchor = match.group(1), match.group(2) or ""
        # Links are emitted as bare slugs, but tolerate a path prefix (`./overview.md`).
        slug = target.rsplit("/", 1)[-1]
        return f"]({name_map.get(slug, slug)}{anchor})"

    return _PAGE_LINK_RE.sub(replace, text)


def render_sidebar(pages: list[dict], name_map: dict[str, str]) -> str:
    """Nav for every page, in taxonomy order — the wiki has no built-in ordered index."""
    lines = ["### Contents", ""]
    for page in sorted(pages, key=lambda p: p["order"]):
        name = name_map[page["slug"]]
        lines.append(f"- [{page['title']}]({name})")
    return "\n".join(lines) + "\n"


def render_footer(manifest: dict, web_url: str, sha: str) -> str:
    """Provenance line: which commit these pages describe, and what wrote them."""
    model = manifest.get("model", "unknown")
    generated = manifest.get("generated_at", "")[:10]
    return (
        f"Generated by [codewiki](https://github.com/doxiebuilds/codewiki) from "
        f"[`{sha}`]({web_url}/tree/{sha}) on {generated} · model `{model}` · "
        f"edits here are overwritten — change `docs/wiki/` in the source repo instead\n"
    )


def build(wiki_dir: Path, out_dir: Path, web_url: str, sha: str) -> list[str]:
    """Write the wiki-shaped copy of `wiki_dir` into `out_dir`. Returns the page names written."""
    manifest_path = wiki_dir / "manifest.json"
    if not manifest_path.exists():
        raise SystemExit(f"no manifest at {manifest_path} — run `codewiki assemble` first")

    manifest = json.loads(manifest_path.read_text())
    pages = manifest["pages"]
    name_map = build_name_map(pages)

    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    written = []
    for page in sorted(pages, key=lambda p: p["order"]):
        source = wiki_dir / page["file"]
        if not source.exists():
            raise SystemExit(f"manifest lists {page['file']} but it's missing from {wiki_dir}")
        name = name_map[page["slug"]]
        (out_dir / f"{name}.md").write_text(rewrite_links(source.read_text(), name_map))
        written.append(name)

    (out_dir / f"{SIDEBAR_PAGE}.md").write_text(render_sidebar(pages, name_map))
    (out_dir / f"{FOOTER_PAGE}.md").write_text(render_footer(manifest, web_url, sha))
    # Carried along for provenance: the wiki lists only markup files as pages, so this is inert.
    shutil.copyfile(manifest_path, out_dir / "manifest.json")

    orphans = sorted(p.name for p in wiki_dir.glob("*.md") if p.name not in {q["file"] for q in pages})
    for orphan in orphans:
        print(f"  ! {orphan} is not in the manifest — not published", file=sys.stderr)

    return written


def clone_wiki(remote: str, dest: Path) -> None:
    try:
        run("git", "clone", "--depth", "1", remote, str(dest))
    except RuntimeError as exc:
        if "not found" in str(exc).lower():
            raise SystemExit(
                f"{remote} does not exist yet.\n"
                "GitHub only creates the wiki repo once wikis are enabled and a first page "
                "exists: Settings > Features > Wikis, then open the repo's Wiki tab and save "
                "any page. Re-run afterwards."
            ) from exc
        raise


def push(out_dir: Path, remote: str, message: str) -> bool:
    """Mirror `out_dir` into the wiki repo. Returns False when nothing changed."""
    with tempfile.TemporaryDirectory() as tmp:
        clone = Path(tmp) / "wiki"
        clone_wiki(remote, clone)

        for item in clone.iterdir():
            if item.name == ".git":
                continue
            shutil.rmtree(item) if item.is_dir() else item.unlink()
        for item in out_dir.iterdir():
            shutil.copyfile(item, clone / item.name)

        run("git", "add", "-A", cwd=clone)
        if not run("git", "status", "--porcelain", cwd=clone):
            return False

        # The wiki repo has no committer identity of its own; CI runners have none at all.
        run("git", "-c", "user.name=codewiki", "-c", "user.email=codewiki@users.noreply.github.com",
            "commit", "-m", message, cwd=clone)
        run("git", "push", "origin", "HEAD", cwd=clone)
        return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    parser.add_argument("--wiki-dir", type=Path, default=DEFAULT_WIKI_DIR,
                        help="generated wiki to publish (default: docs/wiki)")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT_DIR,
                        help="where to write the transformed pages (default: build/wiki)")
    parser.add_argument("--push", action="store_true",
                        help="commit and push the result to the wiki repo (overwrites it)")
    parser.add_argument("--remote", help="wiki remote (default: origin with .wiki.git suffix)")
    parser.add_argument("--message", help="commit message (default: references the source commit)")
    args = parser.parse_args()

    origin = run("git", "remote", "get-url", "origin", cwd=REPO_ROOT)
    web_url = repo_web_url(origin)
    sha = run("git", "rev-parse", "--short", "HEAD", cwd=REPO_ROOT)

    written = build(args.wiki_dir, args.out, web_url, sha)
    print(f"built {len(written)} pages into {args.out.relative_to(REPO_ROOT)}: {', '.join(written)}")

    if not args.push:
        print("review them, then re-run with --push")
        return 0

    remote = args.remote or f"{web_url}.wiki.git"
    changed = push(args.out, remote, args.message or f"Sync wiki from {sha}")
    print(f"pushed to {web_url}/wiki" if changed else "wiki already up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
